# Site settings
title: pmeasyr
email: guillaume.pressiat@chu-brest.fr
description: > # this means to ignore newlines until "baseurl:"
  pmeasyr : import de données PMSI avec R
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://guillaumepressiat.github.io/" # the base hostname & protocol for your site
github_username:  GuillaumePressiat
comment: true
disqus: pmeasyr

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "statisticien"
excerpt_separator: "<!--more-->"

exclude:
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-feed
  - jekyll-seo-tag

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""