# Site settings
title: pmeasyr
email: guillaume.pressiat@aphp.fr
description: > # this means to ignore newlines until "baseurl:"
  pmeasyr : import de données PMSI avec R
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  GuillaumePressiat

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "statisticien"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""