# Site settings
title: Données PMSI avec R
email: guillaume.pressiat@aphp.fr
description: > # this means to ignore newlines until "baseurl:"
  Write an awes escription for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "~/Documents/test-jek2" # the base hostname & protocol for your site
github_username:  GuillaumePressiat

# Other options
permalink: blog/:year/:month/:title
job.title: "statisticien"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""